#ifndef AIRCRAFTCASINGVIBRATESYSTEMCONTROLLER_H
#define AIRCRAFTCASINGVIBRATESYSTEMCONTROLLER_H


class AirCraftCasingVibrateSystemController
{
public:
    AirCraftCasingVibrateSystemController();
};

#endif // AIRCRAFTCASINGVIBRATESYSTEMCONTROLLER_H
